// <auto-generated />
using DatabaseConstructor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseConstructor.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250318004052_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("DatabaseConstructor.InstallmentsTable", b =>
                {
                    b.Property<int>("InstallmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Paid")
                        .HasColumnType("INTEGER");

                    b.Property<float>("PaidValue")
                        .HasColumnType("REAL");

                    b.Property<int>("PaymentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("paymentInfoPaymentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InstallmentId");

                    b.HasIndex("paymentInfoPaymentId");

                    b.ToTable("InstallmentsTable");
                });

            modelBuilder.Entity("DatabaseConstructor.PaymentInfo", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstallmentsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PricePaid")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalInstallments")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("REAL");

                    b.HasKey("PaymentId");

                    b.ToTable("PaymentInfos");
                });

            modelBuilder.Entity("DatabaseConstructor.InstallmentsTable", b =>
                {
                    b.HasOne("DatabaseConstructor.PaymentInfo", "paymentInfo")
                        .WithMany("installmentsTable")
                        .HasForeignKey("paymentInfoPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("paymentInfo");
                });

            modelBuilder.Entity("DatabaseConstructor.PaymentInfo", b =>
                {
                    b.Navigation("installmentsTable");
                });
#pragma warning restore 612, 618
        }
    }
}
