<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Database\**" />
    <EmbeddedResource Remove="Database\**" />
    <None Remove="Database\**" />
    <Page Remove="Database\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Icons\edit-icon.png" />
    <None Remove="Icons\white-arrow-to-left.png" />
    <None Remove="Icons\white-arrow-to-right.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Icons\white-arrow-to-left.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DatabaseAcess\DatabaseAcess.csproj" />
    <ProjectReference Include="..\DatabaseApp\DatabaseConstructor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Icons\edit-icon.png" />
    <Resource Include="Icons\white-arrow-to-right.png" />
  </ItemGroup>

</Project>
